module.exports = {
  '前端': 'web',
  "前端基础": "web-base",
  "前端进阶": "web-advanced",
  "前端高级": "web-senior",
  '前端性能优化': 'performance',
  '前端可视化': 'visual',
  '前端规范': 'web-standard',
  '前端资源': 'web-resources',
  '基础类型': 'basic-type',
  'UI框架': 'ui-framework',
  "Cesium": "cesium",
  '理论工具': 'thoery',

  'Java基础': 'java-base',
  'Java框架': 'java-framework',
  'Java资源': 'java-resources',

  '资源': 'resources',
  '周刊': 'weekly',
  '移动开发': 'app',
  '设计': 'design',
  '停更': 'stop',
  '其他': 'other',
  '错误收集': 'errors',
  '网站': 'website',
  '插件': 'plugins',
  '工具': 'tools',
  "算法与数据结构": 'algorithm',
  "设计模式": "design-pattern",
  "开发资源": "dev"
}
